BitCore-executor:
	- name: BitCore-executor
	- details: the bitcore executor
	- image: bitcore-executor:latest
	- ports: 2317
bitcore-execute:
	echo: BitCore-executor
	echo: "inserito tutto"
BitCore-images:
	macos-image:
		- name: macos-image
		- details: the macos image
	windows-image:
		- name: windows-image
		- details: the windows image
	linux-image:
		echo: "select linux distro"
		./2.0-installer.py
BitCore-settings:
	- name: settings
	- details: the settings
	- settings: ./2.0installer.py
