BitCore:
echo: "BitCore engine is online"
echo: "BitCore engine runs jailbreker"
else
echo: "BitCore engine is offline"
echo: "BitCore engine is not running jailbreker"
JailBreaker:
echo: "JailBreaker is online"
echo: "JailBreaker is running"
else
echo: "JailBreaker is offline"
echo: "jailbreker is not running"

